name: Vercel Deploy

env:
  VERCEL_ORG_ID: team_OLVHZ1GDkWtgmKKN2cL2erFH
  VERCEL_PROJECT_ID: prj_lp9klCh9ZPXK8FqwJRTjJATW4oWy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Deploy to Vercel
        run: |
          vercel deploy ${{ github.ref == 'refs/heads/main' && '--prod' || '' }} --token=${{ secrets.VERCEL_TOKEN }}
